/**
 * Exclusive Zone Seeds
 * User segment categories like Corporate, Women, Birthday, Student
 */

import { IExclusiveZone } from '../../models/ExclusiveZone';

export const exclusiveZoneSeeds: Partial<IExclusiveZone>[] = [
  {
    name: 'Student',
    slug: 'student',
    icon: 'school',
    iconColor: '#6366F1',
    backgroundColor: '#EEF2FF',
    description: 'Exclusive offers for students with valid ID',
    shortDescription: 'Student discounts up to 30%',
    eligibilityType: 'student',
    eligibilityDetails: 'Valid student ID or .edu email required',
    verificationRequired: true,
    offersCount: 34,
    isActive: true,
    priority: 100,
  },
  {
    name: 'Corporate',
    slug: 'corporate',
    icon: 'briefcase',
    iconColor: '#0EA5E9',
    backgroundColor: '#E0F2FE',
    description: 'Special deals for corporate employees',
    shortDescription: 'Corporate perks & discounts',
    eligibilityType: 'corporate_email',
    eligibilityDetails: 'Valid corporate email required',
    verificationRequired: true,
    offersCount: 28,
    isActive: true,
    priority: 95,
  },
  {
    name: 'Women',
    slug: 'women',
    icon: 'woman',
    iconColor: '#EC4899',
    backgroundColor: '#FCE7F3',
    description: 'Exclusive offers curated for women',
    shortDescription: 'Women-only deals',
    eligibilityType: 'gender',
    eligibilityDetails: 'Self-declaration in profile',
    verificationRequired: false,
    offersCount: 45,
    isActive: true,
    priority: 90,
  },
  {
    name: 'Birthday',
    slug: 'birthday',
    icon: 'gift',
    iconColor: '#F59E0B',
    backgroundColor: '#FEF3C7',
    description: 'Special treats during your birthday month',
    shortDescription: 'Birthday month specials',
    eligibilityType: 'birthday_month',
    eligibilityDetails: 'Valid during your birthday month',
    verificationRequired: false,
    offersCount: 12,
    isActive: true,
    priority: 88,
  },
  {
    name: 'Senior Citizen',
    slug: 'senior',
    icon: 'heart',
    iconColor: '#10B981',
    backgroundColor: '#D1FAE5',
    description: 'Exclusive discounts for senior citizens (60+)',
    shortDescription: 'Senior citizen benefits',
    eligibilityType: 'age',
    eligibilityDetails: 'Age 60+ verification required',
    verificationRequired: true,
    offersCount: 18,
    isActive: true,
    priority: 85,
  },
  {
    name: 'First Time User',
    slug: 'first-time',
    icon: 'star',
    iconColor: '#8B5CF6',
    backgroundColor: '#EDE9FE',
    description: 'Welcome offers for new users',
    shortDescription: 'New user welcome deals',
    eligibilityType: 'verification',
    eligibilityDetails: 'First order only',
    verificationRequired: false,
    offersCount: 25,
    isActive: true,
    priority: 92,
  },
];

export default exclusiveZoneSeeds;
